todos = [
    {
        "id": 1,
        "todo": "Do something nice for someone I care about",
        "completed": True,
        "userId": 26
    },
    {
        "id": 2,
        "todo": "Memorize the fifty states and their capitals",
        "completed": False,
        "userId": 48
    }, {"id": 3, "todo": "Watch a classic movie", "completed": False, "userId": 4},
    {"id": 4, "todo": "Contribute code or a monetary donation to an open-source software project",
        "completed": False, "userId": 48},
    {"id": 5, "todo": "Solve a Rubik's cube", "completed": False, "userId": 31}, {"id": 6, "todo": "Bake pastries for me and neighbor", "completed": False, "userId": 39}, {"id": 7, "todo": "Go see a Broadway production", "completed": False, "userId": 32}, {"id": 8, "todo": "Write a thank you letter to an influential person in my life", "completed": True, "userId": 13}, {"id": 9, "todo": "Invite some friends over for a game night", "completed": False, "userId": 47}, {"id": 10, "todo": "Have a football scrimmage with some friends", "completed": False, "userId": 19}, {"id": 11, "todo": "Text a friend I haven't talked to in a long time", "completed": False, "userId": 39}, {"id": 12, "todo": "Organize pantry", "completed": True, "userId": 39}, {"id": 13, "todo": "Buy a new house decoration", "completed": False, "userId": 16}, {"id": 14, "todo": "Plan a vacation I've always wanted to take", "completed": False, "userId": 28}, {"id": 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "todo": "Clean out car", "completed": False, "userId": 33}, {"id": 16, "todo": "Draw and color a Mandala", "completed": True, "userId": 24}, {"id": 17, "todo": "Create a cookbook with favorite recipes", "completed": False, "userId": 1}, {"id": 18, "todo": "Bake a pie with some friends", "completed": False, "userId": 1}, {"id": 19, "todo": "Create a compost pile", "completed": True, "userId": 5}, {"id": 20, "todo": "Take a hike at a local park", "completed": True, "userId": 43}, {"id": 21, "todo": "Take a class at local community center that interests you", "completed": False, "userId": 22}, {"id": 22, "todo": "Research a topic interested in", "completed": False, "userId": 4}, {"id": 23, "todo": "Plan a trip to another country", "completed": True, "userId": 37}, {"id": 24, "todo": "Improve touch typing", "completed": False, "userId": 45}, {"id": 25, "todo": "Learn Express.js", "completed": False, "userId": 49}, {"id": 26, "todo": "Learn calligraphy", "completed": False, "userId": 50}, {"id": 27, "todo": "Have a photo session with some friends", "completed": False, "userId": 14}, {"id": 28, "todo": "Go to the gym", "completed": False, "userId": 15}, {"id": 29, "todo": "Make own LEGO creation", "completed": False, "userId": 30}, {"id": 30, "todo": "Take cat on a walk", "completed": False, "userId": 15}
]


quotes = [{"id":1,"quote":"Life isn’t about getting and having, it’s about giving and being.","author":"Kevin Kruse"},
{"id":2,"quote":"Whatever the mind of man can conceive and believe, it can achieve.","author":"Napoleon Hill"},
{"id":3,"quote":"Strive not to be a success, but rather to be of value.","author":"Albert Einstein"},
{"id":4,"quote":"Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.","author":"Robert Frost"},
{"id":5,"quote":"I attribute my success to this: I never gave or took any excuse.","author":"Florence Nightingale"},{"id":6,"quote":"You miss 100% of the shots you don’t take.","author":"Wayne Gretzky"},{"id":7,"quote":"I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.","author":"Michael Jordan"},{"id":8,"quote":"The most difficult thing is the decision to act, the rest is merely tenacity.","author":"Amelia Earhart"},{"id":9,"quote":"Every strike brings me closer to the next home run.","author":"Babe Ruth"},{"id":10,"quote":"Definiteness of purpose is the starting point of all achievement.","author":"W. Clement Stone"},{"id":11,"quote":"We must balance conspicuous consumption with conscious capitalism.","author":"Kevin Kruse"},{"id":12,"quote":"Life is what happens to you while you’re busy making other plans.","author":"John Lennon"},{"id":13,"quote":"We become what we think about.","author":"Earl Nightingale"},{"id":14,"quote":"Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover.","author":"Mark Twain"},{"id":15,"quote":"Life is 10% what happens to me and 90% of how I react to it.","author":"Charles Swindoll"},{"id":16,"quote":"The most common way people give up their power is by thinking they don’t have any.","author":"Alice Walker"},{"id":17,"quote":"The mind is everything. What you think you become.","author":"Buddha"},{"id":18,"quote":"The best time to plant a tree was 20 years ago. The second best time is now.","author":"Chinese Proverb"},{"id":19,"quote":"An unexamined life is not worth living.","author":"Socrates"},{"id":20,"quote":"Eighty percent of success is showing up.","author":"Woody Allen"},{"id":21,"quote":"Your time is limited, so don’t waste it living someone else’s life.","author":"Steve Jobs"},{"id":22,"quote":"Winning isn’t everything, but wanting to win is.","author":"Vince Lombardi"},{"id":23,"quote":"I am not a product of my circumstances. I am a product of my decisions.","author":"Stephen Covey"},{"id":24,"quote":"Every child is an artist.  The problem is how to remain an artist once he grows up.","author":"Pablo Picasso"},{"id":25,"quote":"You can never cross the ocean until you have the courage to lose sight of the shore.","author":"Christopher Columbus"},{"id":26,"quote":"I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.","author":"Maya Angelou"},{"id":27,"quote":"Either you run the day, or the day runs you.","author":"Jim Rohn"},
{"id":28,"quote":"Whether you think you can or you think you can’t, you’re right.","author":"Henry Ford"},
{"id":29,"quote":"The two most important days in your life are the day you are born and the day you find out why.","author":"Mark Twain"},
{"id":30,"quote":"Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.","author":"Johann Wolfgang von Goethe"},
{"id":31,"quote":"The best revenge is massive success.","author":"Frank Sinatra"},
{"id":32,"quote":"People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.","author":"Zig Ziglar"},
{"id":33,"quote":"Life shrinks or expands in proportion to one’s courage.","author":"Anais Nin"},
{"id":34,"quote":"If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.","author":"Vincent Van Gogh"},
{"id":35,"quote":"There is only one way to avoid criticism: do nothing, say nothing, and be nothing.","author":"Aristotle"},
{"id":36,"quote":"Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.","author":"Jesus"},
{"id":37,"quote":"The only person you are destined to become is the person you decide to be.","author":"Ralph Waldo Emerson"},
{"id":38,"quote":"Go confidently in the direction of your dreams.  Live the life you have imagined.","author":"Henry David Thoreau"},
{"id":39,"quote":"When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.","author":"Erma Bombeck"},
{"id":40,"quote":"Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.","author":"Booker T. Washington"}
]
